language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r socialprofile_demo/requirements_dev.txt --download-cache $HOME/.pip-cache"
# command to run tests
script: "python manage.py jenkins socialprofile --coverage-rcfile=devscripts/checkers/coveragerc"
script: "python manage.py pylint socialprofile --pylint-file-output --pylint-rcfile=devscripts/checkers/pylintrc"